### ISSUE TITLE
use_frameworks!

### ISSUE THREAD

**Issue by Akateason** [laughmaker/TWSNS#5]
不支持pod动态库

**Comment by laughmaker** [comment]
这个很久没更新了，现在可能会存在问题，你是集成在swift上面吗？

**Comment by Akateason** [comment]
动态库有很多优点. 
oc也支持, 
pod里面加一句 use_frameworks!

**Comment by laughmaker** [comment]
> 动态库有很多优点.
> oc也支持,
> pod里面加一句 use_frameworks!

嗯。你可以更新一下，或者fork一下也可以，因为很久没写iOS了，所以最近也没维护了。公司现在短期也没做iOS项目的计划。

**Comment by Akateason** [comment]
hmmmm.... 我已经换方案自己实现了...

**Comment by laughmaker** [comment]
> hmmmm.... 我已经换方案自己实现了...

赞
